let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Shoes 1",
    price: 45,
    desc: "The Best Products Of Shoes.",
    img: "images/1.jpg",
  },
  {
    id: "ioytrhndcv",
    name: "Watch 1",
    price: 100,
    desc: "The Best Products Of Watch.",
    img: "images/2.jpg",
  },
  {
    id: "wuefbncxbsn",
    name: "Loptop 1",
    price: 2500,
    desc: "The Best Products Of Laptop.",
    img: "images/3.jpg",
  },
  {
    id: "thyfhcbcv",
    name: "Mobile",
    price: 300,
    desc: "The Best Products Of Loptop.",
    img: "images/4.jpg",
  },
  {
    id: "thiecbawdjksadjk",
    name: "Bags 1",
    price: 25,
    desc: "The Best Products Of Bags.",
    img: "images/5.jpg",
  },
  {
    id: "iuertrywebncdjksadjk",
    name: "Bags 2",
    price: 200,
    desc: "The Best Products Of Bags 2.",
    img: "images/6.jpg",
  },
  {
    id: "thierytbvcbvzdhadjk",
    name: "Watch 2",
    price: 450,
    desc: "The Best Products Of Watch 2.",
    img: "images/7.jpg",
  },
  {
    id: "trfoiwfcnbcawdjksadjk",
    name: "Bags 3",
    price: 5,
    desc: "The Best Products Of Bags 3.",
    img: "images/8.jpg",
  },
  {
    id: "cbvxbcvsceldk",
    name: "Shoes 2",
    price: 85,
    desc: "The Best Products Of Watch 2",
    img: "images/9.jpg",
  },
  {
    id: "oiopijmjkhuihb",
    name: "Shoes 3",
    price: 120,
    desc: "The Best Products Of Shoes 3",
    img: "images/10.jpg",
  },
  {
    id: "oiopijewyiohbjhib",
    name: "Watch 3",
    price: 200,
    desc: "The Best Products Of Watch 3.",
    img: "images/11.jpg",
  },
  {
    id: "rtytytuyuytyytbvncv",
    name: "Shoes 4",
    price: 150,
    desc: "The Best Products Of Shoes 4",
    img: "images/12.jpg",
  },
];
